name: Build & deploy to gh-pages (development)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dev:
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: development
      target_repo: hnuti-brontosaurus/bis-frontend-build-dev
      target_branch: main
    secrets: inherit
