name: Build & deploy to gh-pages (development)

on:
  push:
    branches:
      - deploy-multiple-gh-pages
      - main

environment: development

jobs:
  check:
    run: echo "hello world"
  build-and-deploy-dev:
    environment: development
    uses: hnuti-brontosaurus/bis-frontend/.github/workflows/deploy-env.yml@${{ GITHUB_BASE_REF }}
    with:
      # (required) which environment to run the action with
      # in particular, which environment variables and secrets to use
      environment: development
      # (required) url where the app will live; without protocol (https://) and without trailing slash (/)
      url: ${{ vars.URL }}
      # (required) a repository to push the build to
      target_repo: ${{ vars.TARGET_REPO }}
      # (optional) path to api, if it's on a different domain
      api: ${{ vars.API }}
      # (optional) path to proxy to serve images, if it's on a different domain
      cors_proxy: ${{ vars.CORS_PROXY }}
    secrets:
      # (required)
      target_ssh_key: ${{ secrets.DEPLOY_GH_PAGES_SSH_KEY }}
      # (optional) Sentry DSN, if you want to use Sentry for error reporting
      # beware: this one is actually exposed in the build, not really secret
      sentry_dsn: ${{ secrets.SENTRY_DSN }}
